DiamondLightSource/python-workflows

- setup.py
due to not yet supported API changes
> limit stomp.py to versions <5

- workflows/transport/common_transport.py
- workflows/transport/pika_transport.py
- workflows/transport/stomp_transport.py
- workflows/transport/test_stomp_transport.py
when sending messages.
This is somewhat preferable over crashing, even if it means losing precision.
> turn Decimals into floats

- setup.cfg
- src/workflows/contrib/zocalo_configuration.py
This is using the new Zocalo configuration API (cf. DiamondLightSource/python-zocalo#90), and will only have any effect if a compatible version of Zocalo is installed.
> Add a Zocalo plugin to enable stomp configuration

- src/workflows/recipe/wrapper.py
- src/workflows/transport/common_transport.py
the reconnection mechanism only works on connections that have neither
active subscriptions nor active transactions, as the semantics of those
would be broken by automatic reconnection.
> Add a reconnection mechanism to recipe wrappers

- pytest.ini
so ensure it is present before running tests
> Running tests requires the pytest-timeout plugin

- src/workflows/transport/stomp_transport.py
- tests/transport/test_stomp.py
I believe this is not used anywhere and can be removed safely.
> Remove stomp transport transformation parameter

- src/workflows/contrib/start_service.py
- src/workflows/transport/__init__.py
This reduces copy-pasta in every cli that supports setting transport type.
Make transport_argument optional for backwards compatibility
> Add --transport in transport.add_command_line_options

- src/workflows/services/common_service.py
specifically test_common_service.py::test_log_unknown_band_data.
Shutdown of the queue listener thread doesn't happen immediately as it
also depends on the main thread acting first. Therefore the queue
listener thread may encounter the injected Exception even though all the
events are happening in the right order.
> Fix an otherwise harmless race condition in test

- .azure-pipelines/ci.yml
- tests/transport/test_pika.py
Spin up a RabbitMQ server instance for tests and run tests against the server instance.
Some tests needed amendments, as they modified class variables as an unintended side-effect, or confused class and object variables. I've provided a fixture to help with this.
> Run pika tests on Azure against a real RabbitMQ server

- src/workflows/transport/pika_transport.py
Issue raised by https://github.com/DiamondLightSource/python-zocalo/pull/146 - this should not hold the process open if not shut down correctly.
> Make _PikaThread explicitly daemonic

- requirements_dev.txt
- setup.cfg
- src/workflows/transport/pika_transport.py
- tests/transport/test_pika.py
If a transaction is running on an outgoing channel then all messages
going out on that channel must either match this transaction, or - if
they are outside of a transaction - must be committed immediately.
If a transaction is running, has uncommitted messages, and then a
message is sent outside of a transaction an error must be raised, as
RabbitMQ does not support this behaviour.
The only messages outgoing on a transacting, subscribing channel are
ACK/NACK and transacted sends. (Untransacted sends do not go through
this channel, so do not need to be considered.) In all three cases,
set a flag if there are uncommitted messages on the transaction to
detect the above case, so that an error can be raised.
This adds a package dependency on [bidict](https://pypi.org/project/bidict/) and closes …
> Enforce transaction semantics on RabbitMQ

- src/workflows/transport/common_transport.py
- src/workflows/transport/pika_transport.py
- src/workflows/transport/stomp_transport.py
- src/workflows/util/__init__.py
- tests/transport/test_pika.py
This adds a `subscribe_temporary()` function (with pika and stomp implementations, and full-stack pika tests).
Merging this resolves #105 discussion and closes #100 and closes #95.
> Add common transport API for subscriptions to a temporary queue

- src/workflows/transport/pika_transport.py
That way madness lies. If a subscription is reconnectable then
transactions are not allowed. If you want transactions then you can't
have reconnectability.
> Do not allow reconnectable transactions

- src/workflows/transport/pika_transport.py
- src/workflows/util/zocalo/configuration.py
- tests/transport/test_pika.py
Delayed message exchanges specified with delayed_message_exchange
field in the rabbitmq configuration.
If no delayed message exchange is set, and a message is sent with
a delay, then raise a ValueError.
Otherwise send to the delayed message exchange if a delay is requested,
or to the default exchange if not.
> RMQ: support for delayed message exchanges

- src/workflows/transport/pika_transport.py
Keep track of all Futures that are handed out to calling functions and
ensure that they are either resubmitted on connection
failure/reconnection or are cancelled/raise a Disconnected exception
when the underlying connection has permanently failed.
We noticed that when a connection fails due to an unclean connection loss (in this specific case: client process is suspended, server closes connection, client resumes) that the client connection can be lost with a callback function not being run at all. In that case the future is never touched and remains open forever. This PR ensures we don't lose track of futures.
This probably still does not handle transactions correctly.
> Ensure handed out Futures eventually terminate

- .pre-commit-config.yaml
- requirements_dev.txt
- setup.cfg
- src/workflows/contrib/start_service.py
- src/workflows/recipe/__init__.py
- src/workflows/services/common_service.py
- src/workflows/transport/common_transport.py
- src/workflows/transport/middleware/__init__.py
- src/workflows/transport/middleware/prometheus.py
- src/workflows/transport/offline_transport.py
- src/workflows/transport/pika_transport.py
- src/workflows/transport/stomp_transport.py
- tests/contrib/test_start_service.py
- tests/services/test_sample_producer.py
- tests/transport/test_middleware.py
- tests/transport/test_offline.py
This enables user code to add middleware that can intercept or monitor transport calls. Basic counter and timer middleware
are provided as examples.
Add `PrometheusMiddleware` that can be used to instrument downstream code to collect prometheus metrics for exposing via a prometheus endpoint.
A minimal example to add prometheus instrumentation is:
```
import prometheus_client
from workflows.transport.offline_transport import OfflineTransport
from workflows.transport.middleware.prometheus import PrometheusMiddleware
transport = OfflineTransport()
instrument = PrometheusMiddleware(source="my-service")
transport.add_middleware(instrument)
prometheus_client.start_http_server(8000)
transport.send(...)
```
Add --no-strict-optional and --ignore-missing-imports to mypy pre-commit-config to silence …
> Implementation of transport middleware

- src/workflows/transport/middleware/prometheus.py
- tests/transport/test_middleware.py
So attempt to lookup the `__qualname__` of the `.func` attribute of the partial object
> functools.partial objects don't have __qualname__

- src/workflows/recipe/__init__.py
- src/workflows/recipe/wrapper.py
- tests/recipe/test_wrap_subscription.py
- tests/recipe/test_wrapped_recipe.py
This enables overriding the default message mangling at the recipe/recipe wrapper level, in contrast to #130 which implemented it in the lower-level transport level. As pointed out in https://github.com/DiamondLightSource/python-workflows/pull/130#issuecomment-1128858529 and https://github.com/DiamondLightSource/python-workflows/pull/130#issuecomment-1129066131 there are alternative ways you can implement custom mangling at the pure transport level, without needing to modify the existing transport interface. However, the existing recipe interface doesn't support custom mangling.
Closes #130
> Enable custom recipe message mangling functions 

- src/workflows/contrib/start_service.py
- src/workflows/transport/middleware/__init__.py
- src/workflows/transport/middleware/prometheus.py
- tests/contrib/test_start_service.py
- tests/transport/test_middleware.py
* Move `get_callback_source()` up to parent middleware module
* Fix service starter transport hook
Since `transport_factory` is usually the transport class, we call the  `__init__` method rather than a `__call__` method, hence the existing implementation would never call the `on_transport_factory_preparation()` hook.
> Improved log format of TimerMiddleware

- src/workflows/transport/middleware/__init__.py
- src/workflows/transport/middleware/prometheus.py
- tests/transport/test_middleware.py
This preserves the wrapped callback name when stacking multiple middleware layers
Add subscribe_broadcast and subscribe_temporary to TimerMiddleware
> Use functools.wraps on when wrapping callbacks

- src/workflows/contrib/start_service.py
- src/workflows/frontend/__init__.py
- src/workflows/services/common_service.py
- tests/contrib/test_start_service.py
- tests/frontend/test_frontend.py
Add a `--liveness` option to zocalo.service which starts a liveness endpoint on the port defined by `--liveness-port`. This sends a message to the frontend, which, if alive, will return a message confirming it is alive. If confirmation of aliveness is received, the endpoint will return a 200 status code, else it returns 408 Request Timeout.
This is intended for use as a livenessProbe when running services on Kubernetes. It should force a container restart in the event that a pod is blocked indefinitely.
> Add liveness probe to services

- setup.cfg
For Hyperion some of our dependencies install stomp as `stomp.py` and some as `stomp-py`. Whilst both are valid for `pip` when making an entry point for some reason that we haven't got to the bottom of using `stomp.py` fails (see https://github.com/DiamondLightSource/hyperion/issues/1346). Given that pypi calls it `stomp-py` and recommends you install it as `pip install stomp-py` it seems sensible to change it here rather than try and fix our downstream issues.
> Update stomp dependency to more a standard name

- src/workflows/services/__init__.py
- src/workflows/transport/__init__.py
- tests/services/test.py
- tests/transport/test.py
This fixes issue #180, removing pkg_resources in favour of the standard library importlib.metadata
> (#180) Remove dependency on pkg_resources in favour of importlib

- .azure-pipelines/azure-pipelines.yml
- src/workflows/services/__init__.py
- src/workflows/transport/__init__.py
- tests/services/test.py
- tests/transport/test.py
#181
This ran into the python 3.12 importlib compatibility issue.
This reverts commit 28dc03509b9599fb73100235f3ac5a4fc53d594c.
> Revert "Remove dependency on pkg_resources in favour of importlib"

- src/workflows/contrib/start_service.py
At present, a user can grow accustomed to lazily providing lower-case service names when invoking `workflows.service` from the command line.  This works fine until you encounter the following situation:
- Known services include `DLSISPyB` and `DLSISPyBPIA`;
- user specifies `-s dlsispyb`, expecting this to be interpreted as `DLSISPyB`, or else expecting an error;
- not finding a perfect match, the current logic checks whether any known service names, rendered in lower case, start with `dlsispyb`, finds two such matches;
- rather than selecting either of these two matches, the program quietly continues to open a frontend and doesn't start any service;
- user sees so warning or error, program twiddles its thumbs until manually terminated.
New logic:
1. Check for perfect match;
2. Failing …
> Check a valid service name has been provided
